export const PRODUCTS = [
  {
    id: "p1",
    name: "Executive Leather Wallet Set",
    price: 85.0,
    image: "/products/File 1.jpeg",
    category: "Accessories",
    description: "The ultimate corporate or personal gift. A genuine leather wallet, matching keychain, and smooth-writing ballpoint pen, all beautifully presented and personalized to your specifications.",
    features: ["Genuine Leather Wallet", "Matching personalized keychain", "Premium smooth ink pen"],
  },
  {
    id: "p2",
    name: "Classic Pen & Keychain Set",
    price: 45.0,
    image: "/products/File 2.jpeg",
    category: "Accessories",
    description: "A timeless combo for professionals. Includes an engraved faux-leather keychain and a matching premium silver and black pen. Perfect for work anniversaries and corporate milestones.",
    features: ["Textured leather keychain", "Smooth writing executive pen", "Elegant display box"],
  },
  {
    id: "p3",
    name: "Classic Wooden Wine Accessory Set",
    price: 55.0,
    image: "/products/File 3.jpeg",
    category: "Drinkware",
    description: "Elegant wooden-handled corkscrew and a beautifully matching wood-top bottle stopper. The perfect addition to any wine lover's collection.",
    features: ["Wood finish accents", "Stainless steel corkscrew", "Premium tan gift box"],
  },
  {
    id: "p4",
    name: "Matte Black Wine Toolkit",
    price: 65.0,
    image: "/products/File 4.jpeg",
    category: "Drinkware",
    description: "A sleek, moody matte black wine accessory set. Includes a heavy-duty corkscrew, a modern bottle stopper, and foil cutter. Ideal for weddings and groomsmen.",
    features: ["Matte black finish", "Complete wine toolkit", "Luxury unboxing experience"],
  },
  {
    id: "p5",
    name: "Premium Wooden Corkscrew & Stopper",
    price: 50.0,
    image: "/products/File 5.jpeg",
    category: "Drinkware",
    description: "A beautifully crafted wooden corkscrew and matching bottle stopper set, presented in an elegant tan box. Ready for deep laser engraving.",
    features: ["Ergonomic wooden handle", "Durable stainless steel", "Perfect for wine enthusiasts"],
  },
  {
    id: "p6",
    name: "Executive Black Cardholder Set",
    price: 75.0,
    image: "/products/File 6.jpeg",
    category: "Accessories",
    description: "A sophisticated matching black cardholder, sleek keychain, and executive pen set. Elevate your professional everyday carry with personalized touches.",
    features: ["Textured black finish", "Metal-accented card holder", "Professional aesthetics"],
  },
  {
    id: "p7",
    name: "Engraved Leather Pen Pouch",
    price: 35.0,
    image: "/products/File 7.jpeg",
    category: "Accessories",
    description: "A beautiful brown faux-leather pen pouch with a premium silver pen. Customize the pouch with initials or a corporate logo for a memorable gift.",
    features: ["Custom engraving on pouch", "Premium silver pen included", "Elegant & highly portable"],
  },
  {
    id: "p8",
    name: "Custom Corporate Gifting Bundle",
    price: 250.0,
    image: "/products/File 8.jpeg",
    category: "Accessories",
    description: "Explore our full range of personalized giftware. From engraved flasks and mugs to executive leather sets, we have everything you need for high-voltage customization.",
    features: ["Mix and match products", "Bulk corporate discounts", "Deep laser engraving"],
  }
];
