export const PRODUCTS = [
  {
    id: "p1",
    name: "Premium Glass Beer Mug",
    price: 35.0,
    image: "/products/File 1.jpeg",
    category: "Drinkware",
    description: "Celebrate milestones with a beautifully engraved glass mug. Perfect for birthdays, anniversaries, and special events. High-quality and dishwasher safe.",
    features: ["Holds 500ml", "Dishwasher safe", "Laser engraved precision"],
  },
  {
    id: "p2",
    name: "Executive Leather Wallet Set",
    price: 85.0,
    image: "/products/File 2.jpeg",
    category: "Accessories",
    description: "The ultimate corporate or personal gift. A genuine leather wallet and smooth-writing ballpoint pen, both personalized to your specifications.",
    features: ["Genuine Leather", "Multiple card slots", "Premium smooth ink pen"],
  },
  {
    id: "p3",
    name: "Classic Pen & Keychain",
    price: 45.0,
    image: "/products/File 3.jpeg",
    category: "Accessories",
    description: "A timeless combo for professionals. Includes an engraved keychain and a matching premium pen. Perfect for work anniversaries and groom's gifts.",
    features: ["Sleek metal finish", "Smooth writing", "Durable key ring"],
  },
  {
    id: "p4",
    name: "Matte Black Flask & Funnel Set",
    price: 55.0,
    image: "/products/File 4.jpeg",
    category: "Drinkware",
    description: "A classy and durable stainless steel flask set. Includes a pouring funnel and steel finish accents. Ideal for weddings and groomsmen.",
    features: ["Stainless Steel 8oz", "Leak-proof cap", "Deep laser engraving"],
  },
  {
    id: "p5",
    name: "Insulated Water Bottle (Pro)",
    price: 40.0,
    image: "/products/File 5.jpeg",
    category: "Drinkware",
    description: "Keep drinks cold for up to 24 hours or hot for 12 hours. Sleek matte black and blue variations. Add a name to make it yours.",
    features: ["Premium Insulation", "Eco-friendly", "Durable matte finish"],
  },
  {
    id: "p6",
    name: "Pastel Teacher Flask",
    price: 38.0,
    image: "/products/File 6.jpeg",
    category: "Drinkware",
    description: "Show your appreciation with a 'World's Best Teacher' personalized pastel flask. Comes with a handy carrying strap.",
    features: ["Double wall insulation", "Soft pastel colors", "Convenient carry strap"],
  },
  {
    id: "p7",
    name: "Custom Engraved Wine Bottle",
    price: 75.0,
    image: "/products/File 7.jpeg",
    category: "Drinkware",
    description: "A stunning fully engraved wine bottle for the ultimate keepsake. Perfect for birthdays or high-end corporate gifts.",
    features: ["Deep glass engraving", "Premium 750ml Wine", "Detailed 360 wrap design"],
  },
  {
    id: "p8",
    name: "Personalized Leather Notebook",
    price: 35.0,
    image: "/products/File 8.jpeg",
    category: "Accessories",
    description: "'Daddy's book of big ideas' or customize it your way! Includes an attached pen holder and bookmark string.",
    features: ["Vegan leather cover", "Lined premium paper", "Includes wooden pen"],
  }
];
